import Crypto
import Foundation

#if canImport(Glibc)
import Glibc
#elseif canImport(Musl)
import Musl
#elseif canImport(Darwin)
import Darwin
#endif

// Streaming age (c2sp.org/age), for files too large to hold in memory
// (attachments, docs/attachments.md §2 "Large files", format.md §8.1.4).
//
// The format is streamable by design (age spec "Payload"): the payload is a
// sequence of independently authenticated ChaCha20-Poly1305 chunks of 64 KiB
// plaintext, so encryption and decryption need memory for one chunk, plus the
// header (capped at 2 MiB, HeaderCodec.maxHeaderBytes) while it is parsed.
// Every path here produces and accepts exactly the bytes the whole-buffer
// `AgeFile.encrypt` / `AgeFile.decrypt` do; only binary files are streamed
// (decode ASCII armor first with `Armor.decode`, or use the buffer API).

// MARK: - Encryption

/// Streaming age encryption: plaintext in, ciphertext out, holding at most
/// one 64 KiB chunk of plaintext.
///
/// Feed plaintext with `update(_:)` in pieces of any size, then call
/// `finish()` once. Concatenated, the returned pieces are a binary age file
/// (header, 16-byte nonce, STREAM payload; age spec "Header", "Payload").
///
/// A full chunk is sealed only once at least one more plaintext byte has
/// arrived, because the final chunk carries a different nonce flag (age spec
/// "Payload": the last chunk is flagged `0x01` and may be short, and is empty
/// only when the whole payload is). So `update` returns ciphertext 64 KiB
/// behind the input, and `finish` seals the rest.
///
/// A class, not a struct: a copy of the stream state would let two different
/// continuations be sealed under the same payload key and chunk counter,
/// which is nonce reuse for ChaCha20-Poly1305. Not thread-safe.
public final class AgeEncryptor {
    private let key: SymmetricKey
    /// Header and nonce, handed out with the first output.
    private var prefix: Data?
    private var pending = Data()
    private var counter: UInt64 = 0
    private var finished = false

    /// Starts a file encrypted to `recipients` under a fresh random file key
    /// and nonce (age spec "File key": generated by a CSPRNG for each file;
    /// "Payload": 16-byte random nonce).
    ///
    /// - Parameter allowMixedPostQuantum: as for `AgeFile.encrypt`.
    /// - Throws: as `AgeFile.encrypt` for the recipients.
    public convenience init(to recipients: [any AgeRecipient], allowMixedPostQuantum: Bool = false) throws {
        let fileKey = FileKey()
        let header = try AgeFile.header(fileKey: fileKey, recipients: recipients,
                                        allowMixedPostQuantum: allowMixedPostQuantum)
        self.init(header: header, fileKey: fileKey, nonce: Data(secureRandomBytes(Stream.nonceSize)))
    }

    /// An encryptor with a given encoded header, file key and nonce. Only for
    /// tests (reproducing known files) and for paths that already built the
    /// header from a fresh key; a file key and nonce must never encrypt two
    /// different payloads.
    init(header: Data, fileKey: FileKey, nonce: Data) {
        key = Stream.payloadKey(fileKey: fileKey, nonce: nonce)
        prefix = header + nonce
        pending.reserveCapacity(Stream.chunkSize)
    }

    /// Adds plaintext and returns the ciphertext that is ready (possibly
    /// empty; the header and nonce come with the first call).
    ///
    /// - Throws: `AgeError.streamFinished` after `finish()` or a failure.
    public func update(_ plaintext: Data) throws -> Data {
        guard !finished else { throw AgeError.streamFinished }
        do {
            var out = takePrefix()
            var offset = plaintext.startIndex
            while true {
                let need = Stream.chunkSize - pending.count
                let available = plaintext.endIndex - offset
                // Keep a full chunk until a byte beyond it shows it is not the last.
                if available <= need {
                    pending += plaintext[offset...]
                    return out
                }
                pending += plaintext[offset..<offset + need]
                offset += need
                out += try sealPending(last: false)
            }
        } catch {
            finished = true
            throw error
        }
    }

    /// Seals the final chunk and returns the remaining ciphertext. The
    /// encryptor cannot be used afterwards.
    ///
    /// - Throws: `AgeError.streamFinished` if called twice or after a failure.
    public func finish() throws -> Data {
        guard !finished else { throw AgeError.streamFinished }
        finished = true
        var out = takePrefix()
        // Empty only when the whole payload is (age spec "Payload").
        out += try sealPending(last: true)
        pending = Data()
        return out
    }

    private func takePrefix() -> Data {
        defer { prefix = nil }
        return prefix ?? Data()
    }

    private func sealPending(last: Bool) throws -> Data {
        // The nonce counter is 11 bytes (age spec "Payload"); 2^64 chunks of
        // 64 KiB cannot occur, but a wrap must never trap or repeat a nonce.
        guard counter < UInt64.max else { throw AgeError.payload }
        let sealed = try Stream.seal(pending, key: key, counter: counter, last: last)
        counter += 1
        pending.removeAll(keepingCapacity: true)
        return sealed
    }
}

// MARK: - Decryption

/// Streaming age decryption: a pull iterator over the authenticated
/// plaintext chunks of a binary age file.
///
/// `init` reads and checks the header (parse, file key unwrap, header MAC,
/// nonce) and throws exactly as `AgeFile.decrypt` would. Then each `next()`
/// reads one sealed chunk (64 KiB + 16), authenticates it and returns its
/// plaintext; `nil` means the final chunk was authenticated and nothing
/// follows it. Memory is one chunk plus the header.
///
/// A chunk is released only after its Poly1305 tag verifies under its
/// position (counter) and final flag, so a reordered, dropped, duplicated or
/// altered chunk is rejected where it occurs (age spec "Payload"). But the
/// stream as a whole is known complete only when `next()` returns `nil`:
/// a file cut at a chunk boundary releases every chunk before the cut and
/// then throws `AgeError.payload`. Callers must treat what they received as
/// unusable unless the iteration ended with `nil` (as age's own reader does,
/// which hands out the same chunks before the same errors).
///
/// After an error every later `next()` throws the same error. Not
/// thread-safe.
public final class AgeDecryptor {
    /// The parsed header (stanzas and MAC), already verified.
    public let header: Header
    /// The unwrapped file key. Internal: only the rewrap needs it.
    let fileKey: FileKey
    /// The 16-byte payload nonce.
    let nonce: Data
    private let key: SymmetricKey
    private var source: ByteSource
    private var counter: UInt64 = 0
    private var state = State.reading
    private var ownedHandle: FileHandle?

    private enum State {
        case reading
        case lastReleased
        case done
        case failed(any Error)
    }

    /// Reads a binary age file from `read`, which returns up to the
    /// requested number of bytes and an empty `Data` at end of input (it may
    /// return fewer bytes before the end). Errors it throws are passed
    /// through unchanged.
    ///
    /// - Throws: header failures as `AgeFile.decrypt` (`headerParse`,
    ///   `unsupportedVersion`, `invalidStanza`, `scryptNotAlone`,
    ///   `scryptWorkFactor`, `noIdentities`, `noMatchingIdentity`,
    ///   `headerMAC`); `headerParse` for ASCII-armored input.
    public init(identities: [any AgeIdentity], read: @escaping (Int) throws -> Data) throws {
        var source = ByteSource(read: read)
        let (header, _) = try Self.readHeader(&source)
        let fileKey = try AgeFile.unwrapFileKey(header: header, identities: identities)
        // A file that ends before the 16-byte nonce is a header-level
        // failure, as in the reference implementation and AgeFile.decrypt.
        let nonce = try source.readFull(Stream.nonceSize)
        guard nonce.count == Stream.nonceSize else { throw AgeError.headerParse }
        self.header = header
        self.fileKey = fileKey
        self.nonce = nonce
        self.key = Stream.payloadKey(fileKey: fileKey, nonce: nonce)
        self.source = source
    }

    /// Decrypts an in-memory binary age file chunk by chunk.
    public convenience init(_ ciphertext: Data, identities: [any AgeIdentity]) throws {
        var offset = ciphertext.startIndex
        try self.init(identities: identities) { n in
            let end = offset + min(n, ciphertext.endIndex - offset)
            defer { offset = end }
            return Data(ciphertext[offset..<end])
        }
    }

    /// Decrypts from an open file handle, reading from its current offset.
    /// The handle stays open; read failures throw `AgeError.io`.
    public convenience init(reading handle: FileHandle, identities: [any AgeIdentity]) throws {
        try self.init(identities: identities) { n in try FileStreams.read(handle, upTo: n) }
    }

    /// Decrypts the binary age file at `url`. The file stays open until the
    /// decryptor is released.
    ///
    /// - Throws: `AgeError.io` if it cannot be opened or read, else as
    ///   `init(identities:read:)`.
    public convenience init(contentsOf url: URL, identities: [any AgeIdentity]) throws {
        let handle = try FileStreams.openForReading(url)
        do {
            try self.init(reading: handle, identities: identities)
        } catch {
            try? handle.close()
            throw error
        }
        ownedHandle = handle
    }

    deinit {
        try? ownedHandle?.close()
    }

    /// The next authenticated plaintext chunk (at most 64 KiB; empty only for
    /// an empty file), or `nil` once the final chunk has been released and
    /// the input is known to end there.
    ///
    /// - Throws: `AgeError.payload` for a chunk that does not authenticate,
    ///   a missing or empty final chunk, or data after the final chunk;
    ///   errors of the reader; `streamFinished` never (a finished stream
    ///   keeps returning `nil`).
    public func next() throws -> Data? {
        try nextSealed()?.plain
    }

    /// Like `next()`, also returning the sealed chunk as read (ciphertext and
    /// tag), for copying a payload unchanged after authenticating it.
    func nextSealed() throws -> (sealed: Data, plain: Data)? {
        switch state {
        case .done:
            return nil
        case .failed(let error):
            throw error
        case .lastReleased:
            // No trailing data after the final chunk (reference
            // implementation: "trailing data after end of encrypted file").
            // Checked on the call after the final chunk, as age does.
            do {
                guard try source.readFull(1).isEmpty else { throw AgeError.payload }
            } catch {
                state = .failed(error)
                throw error
            }
            state = .done
            return nil
        case .reading:
            do {
                let (sealed, plain, last) = try readChunk()
                state = last ? .lastReleased : .reading
                return (sealed, plain)
            } catch {
                state = .failed(error)
                throw error
            }
        }
    }

    /// One STREAM chunk, mirroring `filippo.io/age/internal/stream`
    /// `Reader.readChunk` (age spec "Payload").
    private func readChunk() throws -> (sealed: Data, plain: Data, last: Bool) {
        let sealed = try source.readFull(Stream.encryptedChunkSize)
        // A message can't end without a chunk marked final.
        guard !sealed.isEmpty else { throw AgeError.payload }
        // A short chunk is necessarily the last one.
        var last = sealed.count < Stream.encryptedChunkSize
        // The final chunk may be short but not empty, unless it is the only
        // chunk (an empty payload).
        if last && counter != 0 && sealed.count == Stream.tagSize { throw AgeError.payload }
        guard sealed.count >= Stream.tagSize else { throw AgeError.payload }
        guard counter < UInt64.max else { throw AgeError.payload }
        var plain = Stream.open(sealed, key: key, counter: counter, last: last)
        if plain == nil && !last {
            // A full-length chunk may also be the final one.
            last = true
            plain = Stream.open(sealed, key: key, counter: counter, last: true)
        }
        guard let plain else { throw AgeError.payload }
        counter += 1
        return (sealed, plain, last)
    }

    /// Reads the header from `source` and parses it with the same strict
    /// parser as the buffer API. Returns the header and its length in bytes
    /// (the nonce follows), leaving any bytes read past it in `source`.
    ///
    /// The header ends with the first line that starts with `---` (age spec
    /// "Header": the version line is fixed, stanza lines start with `->` and
    /// stanza bodies are base64, so no earlier line can), so the header is
    /// parsed once that line's LF has been read. At most
    /// `HeaderCodec.maxHeaderBytes` (plus one read) is buffered.
    static func readHeader(_ source: inout ByteSource) throws -> (Header, Int) {
        let blockSize = 4096
        var buffer = Data()
        var scan = MacScan()
        while true {
            if let end = macLineEnd(buffer, scan: &scan) {
                let (header, start) = try HeaderCodec.parse(buffer.prefix(end))
                guard start == end else { throw AgeError.headerParse }
                source.unread(Data(buffer[end...]))
                return (header, end)
            }
            // Out of input or over the cap without a MAC line: the strict
            // parser reports why (bad version, bad stanza, truncation).
            if buffer.count > HeaderCodec.maxHeaderBytes {
                _ = try HeaderCodec.parse(buffer)
                throw AgeError.headerParse
            }
            let more = try source.readSome(blockSize)
            if more.isEmpty {
                _ = try HeaderCodec.parse(buffer)
                throw AgeError.headerParse
            }
            buffer += more
        }
    }

    /// Where `macLineEnd` stopped: the next offset to look at for the MAC
    /// line, then (once found) for its LF. Each byte is looked at a bounded
    /// number of times however small the reads.
    struct MacScan {
        var from = 0
        var macStart: Int?
        var lfFrom = 0
    }

    /// The offset just past the LF that ends the first line starting with
    /// `---` after the first line, or nil if not read yet. `scan` keeps the
    /// search linear over repeated calls: a MAC line whose LF has not come
    /// yet is not searched again from its start (with 1-byte reads that made
    /// a 2 MiB unterminated line take minutes).
    static func macLineEnd(_ buffer: Data, scan: inout MacScan) -> Int? {
        let bytes = buffer
        if scan.macStart == nil {
            var i = scan.from
            while i + 4 <= bytes.count {
                if bytes[i] == 0x0A && bytes[i + 1] == 0x2D && bytes[i + 2] == 0x2D && bytes[i + 3] == 0x2D {
                    scan.macStart = i
                    scan.lfFrom = i + 1
                    break
                }
                i += 1
            }
            guard scan.macStart != nil else {
                scan.from = max(0, bytes.count - 3)
                return nil
            }
        }
        guard let lf = bytes[scan.lfFrom...].firstIndex(of: 0x0A) else {
            scan.lfFrom = bytes.count
            return nil
        }
        return lf + 1
    }
}

// MARK: - File and header operations

extension AgeFile {
    /// Encrypts the file at `input` into a new file at `output`, streaming
    /// (memory for one chunk). The output is created with mode 0600 and must
    /// not exist; on any failure it is removed. It is flushed to disk
    /// (`fsync`) before returning; renaming it into place atomically is the
    /// caller's business (docs/io.md).
    ///
    /// - Throws: as `AgeFile.encrypt` for the recipients, `AgeError.io` for
    ///   the files (an existing `output` included).
    public static func encrypt(contentsOf input: URL, to output: URL, recipients: [any AgeRecipient],
                               allowMixedPostQuantum: Bool = false) throws
    {
        let source = try FileStreams.openForReading(input)
        defer { try? source.close() }
        let encryptor = try AgeEncryptor(to: recipients, allowMixedPostQuantum: allowMixedPostQuantum)
        try FileStreams.writeNew(output) { write in
            while true {
                let chunk = try FileStreams.read(source, upTo: Stream.chunkSize)
                if chunk.isEmpty { break }
                try write(try encryptor.update(chunk))
            }
            try write(try encryptor.finish())
        }
    }

    /// Encrypts a sequence of plaintext pieces (of any sizes) into a new file
    /// at `output`, streaming. File handling as
    /// `encrypt(contentsOf:to:recipients:allowMixedPostQuantum:)`; an error
    /// thrown while producing the pieces is not possible with `Sequence`, so
    /// producers that can fail should drive an `AgeEncryptor` directly.
    public static func encrypt<S: Sequence>(_ chunks: S, to output: URL, recipients: [any AgeRecipient],
                                            allowMixedPostQuantum: Bool = false) throws where S.Element == Data
    {
        let encryptor = try AgeEncryptor(to: recipients, allowMixedPostQuantum: allowMixedPostQuantum)
        try FileStreams.writeNew(output) { write in
            for chunk in chunks { try write(try encryptor.update(chunk)) }
            try write(try encryptor.finish())
        }
    }

    /// Decrypts the binary age file at `input` into a new file at `output`
    /// (mode 0600, must not exist), streaming. The output is removed unless
    /// the whole file authenticated, so a damaged input never leaves a partial
    /// plaintext behind. Chunks are written as they authenticate, so a process
    /// killed midway does leave one at `output`: write to a temporary name and
    /// rename it into place once this returns (docs/io.md).
    ///
    /// - Throws: as `AgeDecryptor`, `AgeError.io` for the files.
    public static func decrypt(contentsOf input: URL, to output: URL, identities: [any AgeIdentity]) throws {
        let decryptor = try AgeDecryptor(contentsOf: input, identities: identities)
        try FileStreams.writeNew(output) { write in
            while let chunk = try decryptor.next() { try write(chunk) }
        }
    }

    /// Reads and parses only the header of the binary age file at `url`
    /// (no key needed; nothing is authenticated: the MAC needs the file key).
    /// Reads at most the header plus one 4 KiB block.
    public static func readHeader(contentsOf url: URL) throws -> Header {
        let handle = try FileStreams.openForReading(url)
        defer { try? handle.close() }
        var source = ByteSource { n in try FileStreams.read(handle, upTo: n) }
        return try AgeDecryptor.readHeader(&source).0
    }

    /// Header-only rewrap of a binary or armored age file in memory: see
    /// `rewrapHeader(contentsOf:to:identities:recipients:allowMixedPostQuantum:)`.
    /// Armored input gives armored output.
    public static func rewrapHeader(_ file: Data, identities: [any AgeIdentity], recipients: [any AgeRecipient],
                                    allowMixedPostQuantum: Bool = false) throws -> Data
    {
        let armored = Armor.isArmored(file)
        let binary = armored ? try Armor.decode(file) : file
        let decryptor = try AgeDecryptor(binary, identities: identities)
        var out = try header(fileKey: decryptor.fileKey, recipients: recipients,
                             allowMixedPostQuantum: allowMixedPostQuantum)
        out += decryptor.nonce
        while let (sealed, _) = try decryptor.nextSealed() { out += sealed }
        return armored ? Armor.encode(out) : out
    }

    /// Header-only rewrap: writes to `output` (mode 0600, must not exist) a
    /// copy of `input` whose header wraps the same file key to `recipients`,
    /// followed by the unchanged nonce and payload (format.md §8.1.5).
    ///
    /// The file key is unwrapped with `identities` and the old header's MAC
    /// checked; the new header gets one stanza set per recipient and a new
    /// MAC under the same key (age spec "Header": the MAC key is
    /// `HKDF(file key, "header")`, so a new header needs the file key, never
    /// the payload). The payload is copied chunk by chunk and every chunk is
    /// authenticated on the way, so a damaged file fails here (output
    /// removed) instead of being carried forward.
    ///
    /// Keeping the file key means that anyone who can read an old copy of
    /// the header (any old recipient) can also decrypt the new file. That is
    /// fine when recipients are only added; on removal use
    /// `reencrypt(contentsOf:to:identities:recipients:allowMixedPostQuantum:)`
    /// (format.md §8.1.5). No payload is encrypted twice under one key:
    /// the payload bytes are the same bytes.
    ///
    /// - Throws: as `AgeDecryptor` for the input, as `AgeFile.encrypt` for
    ///   the recipients, `AgeError.io` for the files.
    public static func rewrapHeader(contentsOf input: URL, to output: URL, identities: [any AgeIdentity],
                                    recipients: [any AgeRecipient], allowMixedPostQuantum: Bool = false) throws
    {
        let decryptor = try AgeDecryptor(contentsOf: input, identities: identities)
        let newHeader = try header(fileKey: decryptor.fileKey, recipients: recipients,
                                   allowMixedPostQuantum: allowMixedPostQuantum)
        try FileStreams.writeNew(output) { write in
            try write(newHeader + decryptor.nonce)
            while let (sealed, _) = try decryptor.nextSealed() { try write(sealed) }
        }
    }

    /// Full re-encryption: decrypts `input` and encrypts its plaintext to
    /// `recipients` under a fresh file key and nonce, into `output` (mode
    /// 0600, must not exist), streaming. Plaintext exists only one chunk at a
    /// time in memory, never on disk. The output is removed unless the whole
    /// input authenticated.
    ///
    /// - Throws: as `AgeDecryptor` for the input, as `AgeFile.encrypt` for
    ///   the recipients, `AgeError.io` for the files.
    public static func reencrypt(contentsOf input: URL, to output: URL, identities: [any AgeIdentity],
                                 recipients: [any AgeRecipient], allowMixedPostQuantum: Bool = false) throws
    {
        let decryptor = try AgeDecryptor(contentsOf: input, identities: identities)
        let encryptor = try AgeEncryptor(to: recipients, allowMixedPostQuantum: allowMixedPostQuantum)
        try FileStreams.writeNew(output) { write in
            while let chunk = try decryptor.next() { try write(try encryptor.update(chunk)) }
            try write(try encryptor.finish())
        }
    }
}

// MARK: - Byte sources and files

/// A pull source with a small push-back buffer (the bytes read past the
/// header).
struct ByteSource {
    let read: (Int) throws -> Data
    /// Bytes to hand out before reading again, from `offset` on (an offset,
    /// not re-slicing: a reader that returns far more than asked would
    /// otherwise have its leftover copied on every call).
    private var pending = Data()
    private var offset = 0
    private var atEnd = false

    init(read: @escaping (Int) throws -> Data) {
        self.read = read
    }

    /// Puts bytes back in front of the source.
    mutating func unread(_ data: Data) {
        pending = data + pending[(pending.startIndex + offset)...]
        offset = 0
    }

    /// Up to `max` bytes; empty only at the end of input.
    mutating func readSome(_ max: Int) throws -> Data {
        if offset < pending.count {
            let n = min(max, pending.count - offset)
            let from = pending.startIndex + offset
            let out = Data(pending[from..<(from + n)])
            offset += n
            if offset == pending.count {
                pending = Data()
                offset = 0
            }
            return out
        }
        if atEnd { return Data() }
        let data = try read(max)
        if data.isEmpty {
            atEnd = true
            return data
        }
        // A reader that returns more than asked keeps the rest for later.
        if data.count > max {
            pending = Data(data)
            offset = max
            return Data(pending.prefix(max))
        }
        return Data(data)
    }

    /// Exactly `count` bytes, or fewer only at the end of input.
    mutating func readFull(_ count: Int) throws -> Data {
        var out = Data()
        out.reserveCapacity(count)
        while out.count < count {
            let piece = try readSome(count - out.count)
            if piece.isEmpty { break }
            out += piece
        }
        return out
    }
}

/// File plumbing for the streaming APIs: Foundation plus POSIX `open(2)`,
/// errors as `AgeError.io`.
enum FileStreams {
    static func openForReading(_ url: URL) throws -> FileHandle {
        do { return try FileHandle(forReadingFrom: url) } catch {
            throw AgeError.io("cannot open \(url.path): \(error.localizedDescription)")
        }
    }

    /// Up to `count` bytes; empty at end of file.
    static func read(_ handle: FileHandle, upTo count: Int) throws -> Data {
        do {
            return try drainingAutoreleasePool { try handle.read(upToCount: count) ?? Data() }
        } catch {
            throw AgeError.io("read failed: \(error.localizedDescription)")
        }
    }

    /// Creates `url` (mode 0600, refusing an existing file), lets `body`
    /// write to it, flushes it to disk and closes it. If anything fails the
    /// file is removed and the error rethrown.
    static func writeNew(_ url: URL, _ body: (_ write: (Data) throws -> Void) throws -> Void) throws {
        let fd = url.withUnsafeFileSystemRepresentation { path -> Int32 in
            guard let path else { return -1 }
            return open(path, O_WRONLY | O_CREAT | O_EXCL | O_CLOEXEC, 0o600)
        }
        guard fd >= 0 else {
            let code = errno
            throw AgeError.io("cannot create \(url.path): \(String(cString: strerror(code)))")
        }
        let handle = FileHandle(fileDescriptor: fd, closeOnDealloc: false)
        do {
            try body { data in
                guard !data.isEmpty else { return }
                do {
                    try drainingAutoreleasePool { try handle.write(contentsOf: data) }
                } catch {
                    throw AgeError.io("write \(url.path): \(error.localizedDescription)")
                }
            }
            do {
                try handle.synchronize()
                try handle.close()
            } catch {
                throw AgeError.io("flush \(url.path): \(error.localizedDescription)")
            }
        } catch {
            try? handle.close()
            try? FileManager.default.removeItem(at: url)
            throw error
        }
    }
}

/// Runs `body` in its own autorelease pool on Apple platforms, where
/// `FileHandle` reads and writes may autorelease buffers that would otherwise
/// pile up until the caller's pool drains (a whole file's worth in a loop).
func drainingAutoreleasePool<T>(_ body: () throws -> T) rethrows -> T {
    #if canImport(ObjectiveC)
    return try autoreleasepool { try body() }
    #else
    return try body()
    #endif
}
