#!/usr/bin/env python3
"""Generates Sources/SempereRender/Text/UnicodeTables.swift from the Unicode
Character Database (UCD), for the text layout of exports (docs/attachments.md
§6, task C2): bidirectional classes and brackets (UAX #9), line break classes
and East Asian widths (UAX #14), scripts (font choice and the missing-script
report), joining types (Arabic shaping) and general categories.

Usage: python3 scripts/generate-unicode-tables.py [UCD_DIR]
UCD_DIR defaults to /usr/share/unicode (Debian/Ubuntu package `unicode-data`).
The UCD is under the Unicode License v3 (permissive); the generated tables
are data derived from it.

Each property is a run table: the code space 0...10FFFF split into runs of
equal value, written as `start:value` pairs (start in base 36, value an
index into the property's value names) in one string literal, which the
Swift side parses on first use. String literals keep compile times low on
CI, where large array literals are slow to type-check.
"""
import os
import re
import sys

UCD = sys.argv[1] if len(sys.argv) > 1 else "/usr/share/unicode"
OUT = os.path.join(os.path.dirname(__file__), "..", "Sources", "SempereRender", "Text", "UnicodeTables.swift")
MAX = 0x110000


def read(path):
    with open(os.path.join(UCD, path), encoding="utf-8") as f:
        return f.read()


def parse_ranges(text, field=1):
    """(lo, hi, value) from `XXXX..YYYY ; value # ...` lines; @missing defaults first."""
    missing, out = [], []
    for line in text.splitlines():
        m = re.match(r"#\s*@missing:\s*([0-9A-F]+)\.\.([0-9A-F]+)\s*;\s*([^;#]+)", line)
        if m:
            missing.append((int(m.group(1), 16), int(m.group(2), 16), m.group(3).strip()))
            continue
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        parts = [p.strip() for p in line.split(";")]
        cps = parts[0].split("..")
        lo = int(cps[0], 16)
        hi = int(cps[-1], 16)
        out.append((lo, hi, parts[field]))
    return missing, out


ALIASES = {}


def load_aliases():
    """Long value names → short ones, per property (PropertyValueAliases.txt)."""
    for line in read("PropertyValueAliases.txt").splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        parts = [p.strip() for p in line.split(";")]
        prop, short = parts[0], parts[1]
        if prop == "ccc":
            continue
        for long_name in parts[2:]:
            ALIASES.setdefault(prop, {})[long_name] = short


def table(text, default, field=1, aliases=None):
    values = [default] * MAX
    missing, ranges = parse_ranges(text, field)
    for lo, hi, v in missing:
        for c in range(lo, hi + 1):
            values[c] = v
    for lo, hi, v in ranges:
        for c in range(lo, hi + 1):
            values[c] = v
    if aliases:
        names = ALIASES[aliases]
        values = [names.get(v, v) for v in values]
    return values


B36 = "0123456789abcdefghijklmnopqrstuvwxyz"


def b36(n):
    if n == 0:
        return "0"
    s = ""
    while n:
        n, r = divmod(n, 36)
        s = B36[r] + s
    return s


def encode(values, names):
    index = {n: i for i, n in enumerate(names)}
    runs = []
    prev = None
    for c, v in enumerate(values):
        if v != prev:
            runs.append("%s:%s" % (b36(c), b36(index[v])))
            prev = v
    return ",".join(runs), len(runs)


def emit(name, doc, values, names):
    names = list(names)
    for v in sorted(set(values)):
        if v not in names:
            names.append(v)
    data, n = encode(values, names)
    lines = ["    /// %s (%d runs)." % (doc, n),
             "    static let %sNames: [String] = [%s]" % (name, ", ".join('"%s"' % v for v in names)),
             '    static let %sRuns = "%s"' % (name, data), ""]
    return "\n".join(lines)


def main():
    version = re.search(r"Version (\d+\.\d+\.\d+)", read("ReadMe.txt")) or re.search(r"(\d+\.\d+\.\d+)", read("extracted/DerivedBidiClass.txt"))
    version = version.group(1)
    parts = ["// Generated by scripts/generate-unicode-tables.py from the Unicode Character",
             "// Database %s. Do not edit; regenerate instead. UCD: Unicode License v3." % version, "",
             "/// Run tables of Unicode properties (see `UnicodeProperties`).",
             "enum UnicodeTables {",
             '    static let version = "%s"' % version, ""]

    load_aliases()
    bidi = table(read("extracted/DerivedBidiClass.txt"), "L", aliases="bc")
    parts.append(emit("bidiClass", "Bidi_Class (UAX #9)", bidi,
                      ["L", "R", "AL", "EN", "ES", "ET", "AN", "CS", "NSM", "BN", "B", "S", "WS", "ON",
                       "LRE", "LRO", "RLE", "RLO", "PDF", "LRI", "RLI", "FSI", "PDI"]))
    lb = table(read("LineBreak.txt"), "XX", aliases="lb")
    parts.append(emit("lineBreak", "Line_Break (UAX #14)", lb, ["XX"]))
    eaw = table(read("EastAsianWidth.txt"), "N", aliases="ea")
    parts.append(emit("eastAsianWidth", "East_Asian_Width", eaw, ["N", "A", "F", "H", "Na", "W"]))
    gc = table(read("extracted/DerivedGeneralCategory.txt"), "Cn", aliases="gc")
    parts.append(emit("generalCategory", "General_Category", gc, ["Cn"]))
    sc = table(read("Scripts.txt"), "Unknown")
    parts.append(emit("script", "Script", sc, ["Unknown", "Common", "Inherited"]))
    jt = table(read("extracted/DerivedJoiningType.txt"), "U", aliases="jt")
    parts.append(emit("joiningType", "Joining_Type (Arabic shaping)", jt, ["U", "R", "L", "D", "C", "T"]))
    ep = ["N"] * MAX
    _, ranges = parse_ranges(read("emoji/emoji-data.txt"))
    for lo, hi, v in ranges:
        if v == "Extended_Pictographic":
            for c in range(lo, hi + 1):
                ep[c] = "Y"
    parts.append(emit("extendedPictographic", "Extended_Pictographic", ep, ["N", "Y"]))

    # Paired brackets (BD14, BD15) and mirrored glyphs (L4).
    pairs = []
    for line in read("BidiBrackets.txt").splitlines():
        line = line.split("#", 1)[0].strip()
        if line:
            a, b, t = [p.strip() for p in line.split(";")]
            pairs.append("%s:%s:%s" % (b36(int(a, 16)), b36(int(b, 16)), t))
    parts.append("    /// Bidi_Paired_Bracket and Bidi_Paired_Bracket_Type (`o` open, `c` close).")
    parts.append('    static let bidiBrackets = "%s"' % ",".join(pairs))
    parts.append("")
    mirrors = []
    for line in read("BidiMirroring.txt").splitlines():
        line = line.split("#", 1)[0].strip()
        if line:
            a, b = [p.strip() for p in line.split(";")]
            mirrors.append("%s:%s" % (b36(int(a, 16)), b36(int(b, 16))))
    parts.append("    /// Bidi_Mirroring_Glyph.")
    parts.append('    static let bidiMirroring = "%s"' % ",".join(mirrors))
    parts.append("}")
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(parts) + "\n")
    print("wrote", OUT, os.path.getsize(OUT), "bytes")


if __name__ == "__main__":
    main()
